<a href="https://colab.research.google.com/github/Saip97/Sql1/blob/main/Copy_of_Problems1to5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problem1

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import torch

In [ ]:
a = np.array([3,4,6,7])#Numpy arrays for storing and manipulating numerical data
print(a)

[3 4 6 7]


#Problem2

In [ ]:
a = np.array([1, 3, 2, 5] , dtype='float32')
print(a)

[1. 3. 2. 5.]


#Problem3

In [ ]:
list_of_lists = [[1, 2, 3],
                 [4, 4, 5],
                 [6, 2, 11]]
b = np.array(list_of_lists)
print(b)

[[ 1  2  3]
 [ 4  4  5]
 [ 6  2 11]]
